export const ADD_ASSET_SYNC = 'ADD_ASSET_SYNC';
export const ADD_INTERSECTION_SYNC = 'ADD_INTERSECTION_SYNC';
export const ADD_RASTER_SYNC = 'ADD_RASTER_SYNC';
export const ADD_TIMESERIES = 'ADD_TIMESERIES';
export const ADD_EVENTSERIES = 'ADD_EVENTSERIES';

export const RECEIVE_ASSET = 'RECEIVE_ASSET';
export const RECEIVE_INTERSECTION = 'RECEIVE_INTERSECTION';
export const RECEIVE_RASTER = 'RECEIVE_RASTER';
export const RECEIVE_EVENTSERIES = 'RECEIVE_EVENTSERIES';

export const REMOVE_TIMESERIES = 'REMOVE_TIMESERIES';
export const REMOVE_ASSET = 'REMOVE_ASSET';
export const REMOVE_INTERSECTION = 'REMOVE_INTERSECTION';
export const REMOVE_RASTER = 'REMOVE_RASTER';
export const REMOVE_EVENTSERIES = 'REMOVE_EVENTSERIES';

export const SET_INTERSECTION_SPACE_TIME = 'SET_SPACE_TIME';
export const TOGGLE_INTERSECTION = 'TOGGLE_INTERSECTION';
