// Usually, for any API request you'll want to dispatch at least three
// different kinds of actions, e.g. for assets:
//
// 1 - ADD_ASSET_SYNC (denotes start of API call)
// 2 - RECEIVE_ASSET_SUCCESS (denotes end of successful API call)
// 3 - RECEIVE_ASSET_FAILURE (denotes end of f*cked API call)

export const ADD_ASSET_SYNC = 'ADD_ASSET_SYNC';
export const ADD_EVENTSERIES_SYNC = 'ADD_EVENTSERIES_SYNC';
export const ADD_INTERSECTION_SYNC = 'ADD_INTERSECTION_SYNC';
export const ADD_RASTER_SYNC = 'ADD_RASTER_SYNC';
export const ADD_TIMESERIES = 'ADD_TIMESERIES';

export const RECEIVE_ASSET_SUCCESS = 'RECEIVE_ASSET_SUCCESS';
export const RECEIVE_ASSET_FAILURE = 'RECEIVE_ASSET_FAILURE';
export const RECEIVE_EVENTSERIES_SUCCESS = 'RECEIVE_EVENTSERIES_SUCCESS';
export const RECEIVE_EVENTSERIES_FAILURE = 'RECEIVE_EVENTSERIES_FAILURE';
export const RECEIVE_INTERSECTION = 'RECEIVE_INTERSECTION';
export const RECEIVE_INTERSECTION_ERROR = 'RECEIVE_INTERSECTION_ERROR';
export const RECEIVE_RASTER_SUCCESS = 'RECEIVE_RASTER_SUCCESS';
export const RECEIVE_RASTER_FAILURE = 'RECEIVE_RASTER_FAILURE';

export const REMOVE_ASSET = 'REMOVE_ASSET';
export const REMOVE_EVENTSERIES = 'REMOVE_EVENTSERIES';
export const REMOVE_INTERSECTION = 'REMOVE_INTERSECTION';
export const REMOVE_RASTER = 'REMOVE_RASTER';
export const REMOVE_TIMESERIES = 'REMOVE_TIMESERIES';

export const SET_INTERSECTION_SPACE_TIME = 'SET_SPACE_TIME';
export const TOGGLE_INTERSECTION = 'TOGGLE_INTERSECTION';
